### ISSUE TITLE
type object 'NDFrame' has no attribute '_set_item'

### ISSUE THREAD

**Issue by gambitov** [kaelzhang/stock-pandas#25]
I updated all repositories and it starts getting an error, may you help?, please

```
Traceback (most recent call last):
  File "analizador.py", line 65, in check_patterns
    signals = binance.analisis(symbol, time_frame)
  File "/home/gabriel/Analizador/binance.py", line 638, in analisis
    TA['EMA10'] = stock['ema:10']
  File "/usr/local/lib/python3.7/dist-packages/stock_pandas/dataframe.py", line 64, in getitem
    key = self._map_single_key(key)
  File "/usr/local/lib/python3.7/dist-packages/stock_pandas/dataframe.py", line 269, in _map_single_key
    column_name, _ = self._get_or_calc_series(directive, True)
  File "/usr/local/lib/python3.7/dist-packages/stock_pandas/dataframe.py", line 316, in _get_or_calc_series
    self._set_new_item(name, array)
  File "/usr/local/lib/python3.7/dist-packages/stock_pandas/dataframe.py", line 331, in _set_new_item
    NDFrame._set_item(self, name, value)
AttributeError: type object 'NDFrame' has no attribute '_set_item'
```

**Comment by kaelzhang** [comment]
Could you follow the issue template and provide the output of the following command?

```sh
python -V
pip list | grep pandas
```

**Comment by gambitov** [comment]
Hello sir, In fact I solved the issue. 
I was using python 3.8.10 and pandas 1.3.1.
To solve it I have to downgrade pandas to 1.2.5.

**Comment by kaelzhang** [comment]
@Flu-iid @gambitov 

[volas](https://github.com/kaelzhang/volas) will be the successor to `stock-pandas`, completely rebuilt using Rust, with a pandas-compatible API and full support for stock indicators aligned with TA-Lib.

`volas`'s stock indicator calculation performance is up to 140x faster than `pandas`, tens of times faster than `stock-pandas`, and its overall performance even surpasses TA-Lib on 146 of 158 indicators
